#Laravel
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www:rw
    container_name: backend
    depends_on:
      - mysql
      # - redis
    networks:
      - laravel

  #nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/:/etc/nginx/conf.d/
    container_name: nginx
    networks:
      - laravel

  #db mysql
  mysql:
      image: mysql:8.0
      platform: linux/x86_64
      restart: unless-stopped
      environment:
          MYSQL_DATABASE: ${DB_DATABASE:-laravel}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
          MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
          MYSQL_USER: ${DB_USERNAME:-username}
          TZ: "America/Sao_Paulo"
      volumes:
          - ./backend/.docker/mysql/dbdata:/var/lib/mysql
      container_name: mysql
      ports:
          - "3306:3306"
      networks:
          - laravel

networks:
  laravel:
    driver: bridge