#Laravel
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:rw
    container_name: backend
    networks:
      - laravel

  #nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    container_name: nginx
    networks:
      - laravel

  #db mysql
  mysql:
      image: mysql:8.0
      platform: linux/x86_64
      restart: unless-stopped
      environment:
          MYSQL_DATABASE: ${DB_DATABASE:-laravel}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
          MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
          MYSQL_USER: ${DB_USERNAME:-username}
      volumes:
          - ./.docker/mysql/dbdata:/var/lib/mysql
      container_name: mysql
      ports:
          - "3306:3306"
      networks:
          - laravel
  # redis
  redis:
      image: redis:latest
      networks:
          - laravel
      container_name: redis
      ports:
          - "6379:6379"

  # queue:
  #     build:
  #         context: ./
  #         dockerfile: Dockerfile
  #     command: php artisan queue:work
  #     restart: unless-stopped
  #     working_dir: /var/www
  #     volumes:
  #         - ./:/var/www:rw
  #     container_name: queue
  #     depends_on:
  #         - redis
  #         - backend
  #     networks:
  #         - laravel

networks:
  laravel:
    driver: bridge